name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Formatter check
        run: deno fmt --check
      - name: Lint
        run: deno lint --unstable
      - name: Run tests
        run: deno test
